name: Run Script

on:
  schedule:
    # Run every day at 18:00 UTC, which is noon CST (not accounting for daylight saving time)
    - cron: '0 18 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run script
      run: ./get_address_info_oAuth_info.sh
